FROM public.ecr.aws/lambda/python:3.13

COPY requirements-derivatives.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r requirements-derivatives.txt

COPY derivatives.py ${LAMBDA_TASK_ROOT}/

CMD ["derivatives.handler"]
